Has the network latency gone up since we switched internet service providers?
* null hyptohesis = Internet service has no impact on network latency
* alternative hypothesis = Newtork latency has gone up since switching internet service providers
* True positive = alpha > p value and we establish that internet service does impact network latency
* True negavite = alpha < p and we establish that internet service has no impact on network latency
* Type 1 error: we reject that internet service has no impact on network latency but the truth is there is no impact
* Type 2 error: we don't reject that internet service has no impact on network latecny but there is significant impact

$H_{0}$ 



Is the website redesign any good?

* null hyptohesis = the website redisign has had no impact on sales
* alternative hypothesis = the webstite redesign has increased sales
* True positive = alpha > p and we establish that the website redesign has increased sales
* True negavite = alpha < p and we establish that the website redesign has had no impact sales
* Type 1 error: we reject that the website redesing has not increased sales but the truth is there is no impact
* Type 2 error: we don't reject that website redesign has had no impact on sales but there has been significant impact

Is our television ad driving more sales?

* null hyptohesis = the television ad has not impacted sales
* alternative hypothesis = the television ad has increased sales
* True positive = alpha > p and we establish that the television ad has increased sales
* True negavite = alpha < p and we establish that the television ad has had no impact sales
* Type 1 error: we reject the null that television ad has not impacted sales bu the truth is there is no impact
* Type 2 error: we don't reject the null that the television ad has had no impact on sales but there has been significant impact


In [149]:
from math import sqrt
from scipy import stats
from pydataset import data
import viz

%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


In [181]:
# Ace Realty wants to determine whether the average time it takes to sell homes is different for its two offices. A sample of 40 sales from office #1 revealed a mean of 90 days and a standard deviation of 15 days. A sample of 50 sales from office #2 revealed a mean of 100 days and a standard deviation of 20 days. Use a .05 level of significance.

    # null = location has no impact on avg home sales time
    # alternative = site a sells houses faster than site b

    # Independent Samples. yes, two separate sample sets

    # Normal Distribution: greater than 30 observations so plenty to meet CLM 

    # Equal Variances:  variances of 219 & 393 not equal

a_mean = 90
a_stddev = 15
b_mean = 100
b_stddev = 20
alpha = 0.05

sitea = np.random.normal(a_mean, a_stddev, 40)
siteb = np.random.normal(b_mean, b_stddev, 50)

sitea.var(), siteb.var()


t, p = stats.ttest_ind(sitea, siteb, equal_var= False)

In [182]:
t, p, alpha

(-3.43464158242499, 0.0009084843336770494, 0.05)

In [47]:
print("is p < alpha? ", p < alpha)
print("is t < 0? ", t < 0)

is p < alpha?  True
is t < 0?  True


In [ ]:
# Load the mpg dataset and use it to answer the following questions:

# Is there a difference in fuel-efficiency in cars from 2008 vs 1999?
# Are compact cars more fuel-efficient than the average car?
# # Do manual cars get better gas mileage than automatic cars?

In [27]:
mpg = data('mpg')
mpg

manufacturer   model  displ  year  cyl       trans drv  cty  hwy fl  \
1           audi      a4    1.8  1999    4    auto(l5)   f   18   29  p   
2           audi      a4    1.8  1999    4  manual(m5)   f   21   29  p   
3           audi      a4    2.0  2008    4  manual(m6)   f   20   31  p   
4           audi      a4    2.0  2008    4    auto(av)   f   21   30  p   
5           audi      a4    2.8  1999    6    auto(l5)   f   16   26  p   
..           ...     ...    ...   ...  ...         ...  ..  ...  ... ..   
230   volkswagen  passat    2.0  2008    4    auto(s6)   f   19   28  p   
231   volkswagen  passat    2.0  2008    4  manual(m6)   f   21   29  p   
232   volkswagen  passat    2.8  1999    6    auto(l5)   f   16   26  p   
233   volkswagen  passat    2.8  1999    6  manual(m5)   f   18   26  p   
234   volkswagen  passat    3.6  2008    6    auto(s6)   f   17   26  p   

       class  
1    compact  
2    compact  
3    compact  
4    compact  
5    compact  
..       ...  
230  midsize  
231  midsize  
232  midsize  
233  midsize  
234  midsize  

[234 rows x 11 columns]

In [73]:
avg_mpg = (mpg['cty'] + mpg['hwy'])/2
eight_fuel = (mpg.year == 2008)
x = mpg[eight_fuel]
nine_fuel = (mpg.year == 1999)
y = mpg[nine_fuel]
y

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact

null_hypothesis = there is no difference in fuel efficiency between the 1999 & 2008

In [97]:
mpg["avg_mpg"] = (mpg.cty + mpg.hwy)/2
avg_08 = mpg[mpg.year == 2008].avg_mpg
avg_99 = mpg[mpg.year == 1999].avg_mpg

In [98]:
# Variance:  Similar
avg_08.var(), avg_99.var()

(24.097480106100797, 27.122605363984682)

In [104]:
# Is there a difference in fuel-efficiency in cars from 2008 vs 1999?  No

t, p = stats.ttest_ind(avg_08, avg_99)

t, p, alpha

(-0.21960177245940962, 0.8263744040323578, 0.05)

In [131]:
# Are compact cars more fuel-efficient than the average car?
mpg["avg_mpg"] = (mpg.cty + mpg.hwy)/2
mpg["avg_mpg"] = (mpg.cty + mpg.hwy)/2
compact = mpg[mpg["class"] == 'compact'].avg_mpg
carpop = mpg["avg_mpg"].mean()


In [125]:
compact.var(), carpop.var()
# 12.4 & 25.5 not the same

(12.442876965772433, 25.50542900113715)

In [132]:

t, p = stats.ttest_1samp(compact, carpop)

t, p/2, alpha

(7.896888573132535, 2.0992818971585668e-10, 0.05)

In [169]:
# Do manual cars get better gas mileage than automatic cars?

mpg["avg_mpg"] = (mpg.cty + mpg.hwy)/2
mpg['auto'] = mpg[mpg['trans'].str.startswith('a')].avg_mpg
mpg['manual'] = mpg[mpg['trans'].str.startswith('m')].avg_mpg
auto = mpg[mpg["a or m"] == 'auto'].avg_mpg
manual = mpg[mpg["a or m"] == 'manual'].avg_mpg

In [171]:
auto.var(), manual.var()

(21.942777233382337, 26.635167464114826)

In [176]:
t, p = stats.ttest_ind(manual, auto, equal_var=False)
t, p, alpha

(4.443514012903071, 1.795224899991793e-05, 0.05)

In [275]:
# Use the telco_churn data. Does tenure correlate with monthly charges? Total charges? What happens if you control for phone and internet service?

df = pd.read_csv('Cust_Churn_Telco.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [278]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [296]:
# Does tenure correlate with monthly charges?
# null_hypothesis: Tenure does not correlate with monthly charges
# alt_hypothesis: Tenure does correlate with monthly charges?
# 0.2478% r score suggests a small correlation and a p score < .01 suggests we can reject the null hypothesis

x = df.tenure
y = df.MonthlyCharges
r, p = stats.pearsonr(x, y)
r, p


(0.2478998562861525, 4.094044991483017e-99)

In [294]:
#  Does tenure correlate with Total charges?
# null_hypothesis: Tenure does not correlate with total charges
# alt_hypothesis: Tenure does correlate with total charges?
# 0.82% r score suggests a large correlation and a p score < .00 suggests we can reject the null hypothesis

x = df.tenure
y = df.TotalCharges.fillna(0)
r, p = stats.pearsonr(x, y)
r, p

(0.8261783979502477, 0.0)

In [314]:
# What happens if you control for phone and internet service?
# Monthly Charges & PhoneService = Yes: r = 0.245 & p =7.11-88.  
x = df['tenure'][df['PhoneService'] == "Yes"]
y = df['MonthlyCharges'][df['PhoneService'] == "Yes"]
r, p = stats.pearsonr(x, y)
r, p

(0.2453889858536324, 7.117871077925186e-88)

In [315]:
# Monthly Charges & PhoneService = No: r = 0.585 & p =4.60-64. 
x = df['tenure'][df['PhoneService'] != "Yes"]
y = df['MonthlyCharges'][df['PhoneService'] != "Yes"]
r, p = stats.pearsonr(x, y)
r, p

(0.5857597986661375, 4.6033703473404816e-64)

# When controlling for PhoneService, tenure impacts MonthlyCharges much more when client does not subscribe to Phone Services.

In [318]:

# Monthly Charges & Internet Service = Yes: r = 0.373 & p =5.85-181.  
x = df['tenure'][df['InternetService'] != "No"]
y = df['MonthlyCharges'][df['InternetService'] != "No"]
r, p = stats.pearsonr(x, y)
r, p

(0.37230662631986955, 5.89096358049607e-181)

In [319]:
# Monthly Charges & Internet Service = No: r = 0.343 & p =3.35-43.  
x = df['tenure'][df['InternetService'] == "No"]
y = df['MonthlyCharges'][df['InternetService'] == "No"]
r, p = stats.pearsonr(x, y)
r, p

(0.34232562306194547, 3.3561869551954843e-43)

# When controlling for Internet Service, tenure does impact MonthlyCharges but the impact is similar whether or not they are an Internet subscriber.


In [4]:
# Use the employees database.
# Is there a relationship between how long an employee has been with the company and their salary?
# # Is there a relationship between how long an employee has been with the company and the number of titles they have had?

import pandas as pd 
import numpy as np
from datetime import date
from env import host, username, password

def get_db_url(host, username, password, database):
    url = f'mysql+pymysql://{username}:{password}@{host}/{database}'
    return url

url = get_db_url(host, username, password, 'employees')


In [5]:
salaries = pd.read_sql('select * from salaries', url)


In [6]:
employees = pd.read_sql('select * from employees', url)

In [7]:
titles = pd.read_sql('select * from titles', url)

In [17]:
# Is there a relationship between how long an employee has been with the company and their salary?

sal_emp = salaries.merge(employees, on='emp_no', how='inner')
sal_emp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2844047 entries, 0 to 2844046
Data columns (total 9 columns):
 #   Column      Dtype 
---  ------      ----- 
 0   emp_no      int64 
 1   salary      int64 
 2   from_date   object
 3   to_date     object
 4   birth_date  object
 5   first_name  object
 6   last_name   object
 7   gender      object
 8   hire_date   object
dtypes: int64(2), object(7)
memory usage: 217.0+ MB


In [37]:
# to convert 9999-01-01 to 2021-05-11 had to change object to byte then to string
sal_emp['to_date'] = sal_emp['to_date'].astype('|S')
sal_emp['to_date'] = sal_emp['to_date'].str.decode('utf-8')
sal_emp['to_date'] = sal_emp['to_date'].str.replace('9999-01-01', '2021-05-11')
sal_emp['to_date'] = pd.to_datetime(sal_emp['to_date'])

In [72]:
from datetime import datetime
sal_emp['to_date'] = pd.to_datetime(sal_emp['to_date'])
sal_emp['hire_date'] = pd.to_datetime(sal_emp['hire_date'])
sal_emp['tenure'] = sal_emp['to_date']-sal_emp['hire_date']


In [91]:
sal_emp.tenure = sal_emp.tenure.astype(int)

In [93]:
x = sal_emp.tenure
y = sal_emp.salary
r, p = stats.pearsonr(x, y)
r, p


(0.3113516051423787, 0.0)

UFuncTypeError: ufunc 'add' cannot use operands with types dtype('float64') and dtype('<m8[ns]')

In [110]:
salary_title_df

emp_no  birth_date first_name last_name gender   hire_date  emp_no  \
0         10001  1953-09-02     Georgi   Facello      M  1986-06-26   10001   
1         10001  1953-09-02     Georgi   Facello      M  1986-06-26   10001   
2         10001  1953-09-02     Georgi   Facello      M  1986-06-26   10001   
3         10001  1953-09-02     Georgi   Facello      M  1986-06-26   10001   
4         10001  1953-09-02     Georgi   Facello      M  1986-06-26   10001   
...         ...         ...        ...       ...    ...         ...     ...   
2844042  499999  1958-05-01     Sachin   Tsukuda      M  1997-11-30  499999   
2844043  499999  1958-05-01     Sachin   Tsukuda      M  1997-11-30  499999   
2844044  499999  1958-05-01     Sachin   Tsukuda      M  1997-11-30  499999   
2844045  499999  1958-05-01     Sachin   Tsukuda      M  1997-11-30  499999   
2844046  499999  1958-05-01     Sachin   Tsukuda      M  1997-11-30  499999   

         salary   from_date     to_date tenure  
0         60117  1986-06-26  1987-06-26 0 days  
1         62102  1987-06-26  1988-06-25 0 days  
2         66074  1988-06-25  1989-06-25 0 days  
3         66596  1989-06-25  1990-06-25 0 days  
4         66961  1990-06-25  1991-06-25 0 days  
...         ...         ...         ...    ...  
2844042   63707  1997-11-30  1998-11-30 0 days  
2844043   67043  1998-11-30  1999-11-30 0 days  
2844044   70745  1999-11-30  2000-11-29 0 days  
2844045   74327  2000-11-29  2001-11-29 0 days  
2844046   77303  2001-11-29  9999-01-01 0 days  

[2844047 rows x 11 columns]

<function date.today>

In [ ]:
salaries_df['to_date']= salaries_df['to_date'].replace(to_replace = salaries_df["to_date"].max(), value =date.today())

In [103]:
# Use the following contingency table to help answer the question of whether using a macbook and being a codeup student are independent of each other.

# Null_Hypothesis = Being a Codeup Student is independent of Macbook Use
# Alt_Hypothesis = Being a Codeup Student is not independent of Macbook use

index = ['Uses a Macbook', 'Doesn\'t Use a Macbook']
columns = ['Codeup Student', 'Not Codeup Student']

observed_mac = pd.DataFrame([[49, 20], [1, 30]], index=index, columns=columns)
observed_mac

Codeup Student  Not Codeup Student
Uses a Macbook                     49                  20
Doesn't Use a Macbook               1                  30

In [104]:
chi2, p, degf, expected = stats.chi2_contingency(observed_mac)

print('Observed\n')
print(observed.values)
print('---\nExpected\n')
print(expected)
print('---\n')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

# Our p is < 0.01 allowing us to reject the Null Hypothesis 

Observed

[[40 20]
 [ 1 30]]
---
Expected

[[34.5 34.5]
 [15.5 15.5]]
---

chi^2 = 36.6526
p     = 0.0000


In [106]:
# # Choose another 2 categorical variables from the mpg dataset and perform a 
#  contingency table test with them. Be sure to state your null and alternative hypotheses.

mpg = data('mpg')
mpg.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 234 entries, 1 to 234
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   manufacturer  234 non-null    object 
 1   model         234 non-null    object 
 2   displ         234 non-null    float64
 3   year          234 non-null    int64  
 4   cyl           234 non-null    int64  
 5   trans         234 non-null    object 
 6   drv           234 non-null    object 
 7   cty           234 non-null    int64  
 8   hwy           234 non-null    int64  
 9   fl            234 non-null    object 
 10  class         234 non-null    object 
dtypes: float64(1), int64(4), object(6)
memory usage: 21.9+ KB


In [113]:
observed_mpg = observed = pd.crosstab(mpg['class'], mpg.cty)
observed_mpg

cty         9   11  12  13  14  15  16  17  18  19  ...  21  22  23  24  25  \
class                                               ...                       
2seater      0   0   0   0   0   3   2   0   0   0  ...   0   0   0   0   0   
compact      0   0   0   0   0   2   3   4   7   5  ...  12   3   0   2   0   
midsize      0   0   0   0   0   1   4   4  13   8  ...   8   1   2   0   0   
minivan      0   1   0   0   0   2   4   3   1   0  ...   0   0   0   0   0   
pickup       3   6   2   8   6   5   2   1   0   0  ...   0   0   0   0   0   
subcompact   0   0   0   0   1   4   2   3   2   6  ...   3   0   1   3   2   
suv          2  13   6  13  12   7   2   1   3   1  ...   0   0   0   0   0   

cty         26  28  29  33  35  
class                           
2seater      0   0   0   0   0  
compact      2   1   0   1   0  
midsize      0   0   0   0   0  
minivan      0   0   0   0   0  
pickup       0   0   0   0   0  
subcompact   1   1   1   0   1  
suv          0   0   0   0   0  

[7 rows x 21 columns]

In [115]:
# Null_hypothesis = City MPG is independent of Auto Class
# Alternative_hypothesis = City MPG correlated with Auto Class
# p < 0.01 leading us to reject the Null_hypothesis and establish some dependence between City mpg and Auto Class

chi2, p, degf, expected = stats.chi2_contingency(observed_mpg)

print('Observed\n')
print(observed.values)
print('---\nExpected\n')
print(expected)
print('---\n')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed

[[ 0  0  0  0  0  3  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  3  4  7  5  5 12  3  0  2  0  2  1  0  1  0]
 [ 0  0  0  0  0  1  4  4 13  8  0  8  1  2  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  2  4  3  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  6  2  8  6  5  2  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  4  2  3  2  6  4  3  0  1  3  2  1  1  1  0  1]
 [ 2 13  6 13 12  7  2  1  3  1  2  0  0  0  0  0  0  0  0  0  0]]
---
Expected

[[0.10683761 0.42735043 0.17094017 0.44871795 0.40598291 0.51282051
  0.40598291 0.34188034 0.55555556 0.42735043 0.23504274 0.49145299
  0.08547009 0.06410256 0.10683761 0.04273504 0.06410256 0.04273504
  0.02136752 0.02136752 0.02136752]
 [1.0042735  4.01709402 1.60683761 4.21794872 3.81623932 4.82051282
  3.81623932 3.21367521 5.22222222 4.01709402 2.20940171 4.61965812
  0.8034188  0.6025641  1.0042735  0.4017094  0.6025641  0.4017094
  0.2008547  0.2008547  0.2008547 ]
 [0.87606838 3.5042735  1.4017094 

In [ ]:
# 3) Use the data from the employees database to answer these questions:

# Is an employee's gender independent of whether an employee works in sales or marketing? (only look at current employees)
 
# Null Hypothesis = Gender is independent of whether an employee works in sales or marketing
#Alternative Hypothesis = Gender is not indepenedent of whether an employee works in sales or marketing

# Our p value > alpha so we can not reject the null hypothesis and there is some relationship b/w gender and Sales/Marketing


In [116]:
dept = pd.read_sql('select * from departments', url)

In [118]:
dept_emp = pd.read_sql('select * from dept_emp', url)

In [119]:
emp = pd.read_sql('select * from employees', url)

In [120]:
dept_emp_merge = dept.merge(dept_emp, on='dept_no', how='inner')

In [162]:
total_merge = dept_emp_merge.merge(emp, on='emp_no', how='inner')
total_merge

dept_no         dept_name  emp_no   from_date     to_date  birth_date  \
0         d009  Customer Service   10011  1990-01-22  1996-11-09  1953-11-07   
1         d009  Customer Service   10038  1989-09-20  9999-01-01  1960-07-20   
2         d009  Customer Service   10049  1992-05-04  9999-01-01  1961-04-24   
3         d009  Customer Service   10060  1992-11-11  9999-01-01  1961-10-15   
4         d007             Sales   10060  1989-05-28  1992-11-11  1961-10-15   
...        ...               ...     ...         ...         ...         ...   
331598    d007             Sales  499976  1988-12-26  9999-01-01  1963-08-20   
331599    d007             Sales  499980  1991-02-11  9999-01-01  1959-06-28   
331600    d007             Sales  499986  1985-08-11  9999-01-01  1952-07-22   
331601    d007             Sales  499987  1999-12-21  9999-01-01  1961-09-05   
331602    d007             Sales  499988  1988-07-25  2001-10-09  1962-09-28   

       first_name    last_name gender   hire_date  
0            Mary        Sluis      F  1990-01-22  
1            Huan        Lortz      M  1989-09-20  
2           Basil       Tramer      F  1992-05-04  
3        Breannda  Billingsley      M  1987-11-02  
4        Breannda  Billingsley      M  1987-11-02  
...           ...          ...    ...         ...  
331598   Guozhong       Felder      M  1988-12-26  
331599       Gino        Usery      M  1991-02-11  
331600     Nathan        Ranta      F  1985-08-11  
331601      Rimli       Dusink      F  1998-09-20  
331602   Bangqing      Kleiser      F  1986-06-06  

[331603 rows x 10 columns]

In [142]:
total_merge_cur = total_merge[total_merge.astype(str).to_date == "9999-01-01"]
total_merge_cur.head()

In [173]:
total_sort = total_merge_cur[(total_merge_cur.dept_name == 'Marketing')|(total_merge_cur.dept_name == 'Sales')]

dept_no dept_name  emp_no   from_date     to_date  birth_date  \
127558    d007     Sales   10050  1992-11-05  9999-01-01  1958-05-21   
127576    d007     Sales   10209  1999-08-07  9999-01-01  1956-12-12   
127603    d007     Sales   10655  2000-11-22  9999-01-01  1959-02-02   
127622    d007     Sales   10855  1997-03-02  9999-01-01  1957-08-07   
127628    d007     Sales   10906  2001-04-25  9999-01-01  1952-02-06   
...        ...       ...     ...         ...         ...         ...   
331596    d007     Sales  499966  1985-06-13  9999-01-01  1955-12-04   
331598    d007     Sales  499976  1988-12-26  9999-01-01  1963-08-20   
331599    d007     Sales  499980  1991-02-11  9999-01-01  1959-06-28   
331600    d007     Sales  499986  1985-08-11  9999-01-01  1952-07-22   
331601    d007     Sales  499987  1999-12-21  9999-01-01  1961-09-05   

       first_name last_name gender   hire_date  
127558    Yinghua    Dredge      M  1990-12-25  
127576      Yolla    Ellozy      F  1991-11-23  
127603      Remko    Dalton      F  1985-07-14  
127622    Kwangho  Reinhart      M  1991-08-05  
127628   Munehiro   Carrere      F  1994-01-20  
...           ...       ...    ...         ...  
331596    Mihalis  Crabtree      F  1985-06-13  
331598   Guozhong    Felder      M  1988-12-26  
331599       Gino     Usery      M  1991-02-11  
331600     Nathan     Ranta      F  1985-08-11  
331601      Rimli    Dusink      F  1998-09-20  

[52543 rows x 10 columns]

In [175]:
observed_gen = pd.crosstab(total_sort.gender, total_sort.dept_name)
observed_gen

dept_name  Marketing  Sales
gender                     
F               5864  14999
M               8978  22702

In [176]:
chi2, p, degf, expected = stats.chi2_contingency(observed_gen)

print('Observed\n')
print(observed.values)
print('---\nExpected\n')
print(expected)
print('---\n')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed

[[ 0  0  0  0  0  3  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  3  4  7  5  5 12  3  0  2  0  2  1  0  1  0]
 [ 0  0  0  0  0  1  4  4 13  8  0  8  1  2  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  2  4  3  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  6  2  8  6  5  2  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  4  2  3  2  6  4  3  0  1  3  2  1  1  1  0  1]
 [ 2 13  6 13 12  7  2  1  3  1  2  0  0  0  0  0  0  0  0  0  0]]
---
Expected

[[ 5893.2426013 14969.7573987]
 [ 8948.7573987 22731.2426013]]
---

chi^2 = 0.3240
p     = 0.5692


In [191]:
# Is an employee's gender independent of whether or not they are or have been a manager?
# Null_hypothesis = Gender is independent of Manager role
# Alt_hypothesis = Gender and Management role have some relationship
# With a p value (0.44) > than our alpha (.05) we can not reject the null hypothesis

In [187]:

emp_man = pd.read_sql('select dept_no, gender from dept_manager join employees using(emp_no)', url)
emp_man

dept_no gender
0     d001      M
1     d001      M
2     d002      M
3     d002      F
4     d003      F
5     d003      F
6     d004      F
7     d004      F
8     d004      M
9     d004      M
10    d005      M
11    d005      F
12    d006      F
13    d006      F
14    d006      F
15    d006      M
16    d007      M
17    d007      M
18    d008      M
19    d008      F
20    d009      F
21    d009      F
22    d009      F
23    d009      M

In [188]:
observed_emp_man = pd.crosstab(emp_man.dept_no, emp_man.gender)
observed_emp_man

gender   F  M
dept_no      
d001     0  2
d002     1  1
d003     2  0
d004     2  2
d005     1  1
d006     3  1
d007     0  2
d008     1  1
d009     3  1

In [190]:
chi2, p, degf, expected = stats.chi2_contingency(observed_emp_man)
print('Observed\n')
print(observed.values)
print('---\nExpected\n')
print(expected)
print('---\n')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed

[[ 0  0  0  0  0  3  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  3  4  7  5  5 12  3  0  2  0  2  1  0  1  0]
 [ 0  0  0  0  0  1  4  4 13  8  0  8  1  2  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  2  4  3  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  6  2  8  6  5  2  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  4  2  3  2  6  4  3  0  1  3  2  1  1  1  0  1]
 [ 2 13  6 13 12  7  2  1  3  1  2  0  0  0  0  0  0  0  0  0  0]]
---
Expected

[[1.08333333 0.91666667]
 [1.08333333 0.91666667]
 [1.08333333 0.91666667]
 [2.16666667 1.83333333]
 [1.08333333 0.91666667]
 [2.16666667 1.83333333]
 [1.08333333 0.91666667]
 [1.08333333 0.91666667]
 [2.16666667 1.83333333]]
---

chi^2 = 7.8881
p     = 0.4445
